### ISSUE TITLE
Bug when hosted behind nginx reverse proxy

### ISSUE THREAD

**Issue by leet1994** [DrewThomasson/ebook2audiobook#130]
I tried to install it on my server behind nginx proxy manager (NPM) and unfortuately the web interface is not showing up.

The ebook2audiobook container reports that it is started and listening on 0.0.0.0:7860. While the container is pingable from inside the NPM container, when visiting the webui, it reports Error 502.

nginx reports the following error in it's logs:
`[error] 6723#6723: *80643 upstream sent too big header while reading response header from upstream`

I was able to fix it by manually increasing the buffer size for this service in NPM:
```
    # Increase buffer sizes
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    large_client_header_buffers 4 16k;
```

**Comment by koassount** [comment]
That’s funny. I solved the same issue 10 minutes ago.
Now I have a new issue though. When trying to download any finished file, you will get redirected to the Docker host’s local IP address to download the files... which obviously won’t work... one can replace the local ip address with the DNS and the files will download. This makes it work, but still not every time clean...
![Screenshot 2024-12-27 at 21 28 34](https://github.com/user-attachments/assets/d93e8ffc-58fc-4d89-ae21-5565aa0e610a)

`const native_fetch = window.fetch;
{
  window.fetch = (input, init) => {
    const method = input instanceof Request ? input.method : (init == null ? void 0 : init.method) || "GET";
    if (method !== "GET") {
      cache.delete(build_selector(input));
    }
    return native_fetch(input, init);
  };
}`

**Comment by ROBERT-MCDOWELL** [comment]
@leet1994 you can x4 all your settings....
@koassount for all reverse proxy you have to use X-Forwarded-For at least.

**Comment by ROBERT-MCDOWELL** [comment]
consider it as solved and btw it's not a bug from ebook2audiobook
