### ISSUE TITLE
Feature Request: Resume started conversions when Docker Container is restarted

### ISSUE THREAD

**Issue by leet1994** [DrewThomasson/ebook2audiobook#131]
Processing ebooks in CPU-only mode is quite slow, therefore it would be good to have the following feature:
When the docker container spins-up, check for already started (but not yet finished) conversions.
If there are any, then resume these conversions.

In my use case, I need to restart the docker container once every day. If a conversion takes longer than one day, it can never finish (because it is aborted as soon as the docker container is stopped).

**Comment by ROBERT-MCDOWELL** [comment]
it's already implemented. just click on the the close X of the ebook file to upload component or just close your browser or Ctrl + C for CLI then when you will run exactly the same ebook file it will resume from the last good sentence.

**Comment by leet1994** [comment]
@ROBERT-MCDOWELL thanks for the reply!
I just tested the following:
* start docker container
* go to webui, upload an ebook and start conversion
* stop docker container
* restart docker container

At this point when visiting the webui again, nothing is restarted automatically. Also, when same ebook is uploaded again, it starts from 0.
As far as I observed, the finished sentences are saved in the tmp folder, which gets cleared when the docker container is restarted (probably a cleanup task from the app.py?).

**Comment by DrewThomasson** [comment]
This might my docker image

I'm in the works on one that's fully based on the repo with its own Dockerfile so it's less buggy 

😅

**Comment by ROBERT-MCDOWELL** [comment]
@leet1994 ok we'll check it asap

**Comment by ROBERT-MCDOWELL** [comment]
@DrewThomasson I have to rebase DockerUtils too....
