### ISSUE TITLE
Feature Request: Integrate apprise to notify when conversion finished

### ISSUE THREAD

**Issue by leet1994** [DrewThomasson/ebook2audiobook#132]
The conversion takes a while, therefore it would be really nice if there is some kind of notification service configurable (i.e. apprise) to notify the user as soon as a conversion is finished.
Probably with the name of the Ebook that was just finished.

**Comment by ROBERT-MCDOWELL** [comment]
on th GUI you have the progress bar and text when it's finished already.
on the CLI, you have everything, progress bar, percentage, each sentence converted, each chapter etc..
didn't you see all these notices?

**Comment by leet1994** [comment]
@ROBERT-MCDOWELL I don't use the CLI, but the docker container with the webui.
If I refresh the page, the progress bar is gone and I've no further information if the conversion is still ongoing.

**Comment by DrewThomasson** [comment]
Working on making a Dockerfile for easy updating rn

sorry about the inconvenience 😅

**Comment by ROBERT-MCDOWELL** [comment]
this is something we cannot implement as it's linux only external application. things are already extremely complex for the base of the project which is provide a high quality TTS in a max of language. If you really want it, just develop it, create a PR, but be sure it should work on all OS like windows/Mac/Linux.
