### ISSUE TITLE
ModuleNotFoundError: No module named 'regex'

### ISSUE THREAD

**Issue by Leon-Sander** [DrewThomasson/ebook2audiobook#135]
When running the bash script this error occurs:
```
Traceback (most recent call last):
  File "/home/leon/code/ebook2audiobook/app.py", line 3, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
```
#133 pull request fixes it by just importing re instead of regex.

If specifically the regex library is necessary for functionality, then the pull request #134 is helpful.
It adds it to requirements.txt where it was missing in the current version of the code.

**Comment by ROBERT-MCDOWELL** [comment]
see #134
