### ISSUE TITLE
con is an invalid folder name (all Windows, but possibly other OSes)

### ISSUE THREAD

**Issue by smallbutfine** [DrewThomasson/ebook2audiobook#136]
Yes, this is an old issue regarding OSes that remain compatible to code going back to the 70's/80's.
con is a reserved name that can not be used as a folder name in several OSes. You used it in the voice files paths.
Therefore I have problems checking out the repository on Windows 10.
Same is for extraction of the release zip file.
I used Nana Zip to automatically rename the invalid folder to _con.
Probably needs some code changes.

**Comment by ROBERT-MCDOWELL** [comment]
duplicate #126

**Comment by DrewThomasson** [comment]
The docker should work as a bandaid solution for you in the mean time 👍

**Comment by smallbutfine** [comment]
Thank you, I used WSL, worked also.
