### ISSUE TITLE
Local URL erroneously reported for the web server.

### ISSUE THREAD

**Issue by smallbutfine** [DrewThomasson/ebook2audiobook#137]
The server console shows
* Running on local URL:  http://0.0.0.0:7860

Should be:
127.0.0.1:7860
(works fine)

OS: Win10 pro

**Comment by ROBERT-MCDOWELL** [comment]
fixed in the next update, thanks

**Comment by ROBERT-MCDOWELL** [comment]
@smallbutfine 
I have to revert it back to 0.0.0.0 to let users have no surprise when they use a Docker...
if you want to run only into 127.0.0.1 so you can changet it in ./lib/conf.py

**Comment by DrewThomasson** [comment]
Having it print out the local host address might be less confusing

**Comment by ROBERT-MCDOWELL** [comment]
You cannot, since 0.0.0.0 means listen on all available host ip addresses.
so it can be 127.0.0.1 and 192.xxx.xxx.xx and etc.... and ip public if the machine is not behind a firewall/router
