### ISSUE TITLE
Running via Docker

### ISSUE THREAD

**Issue by ryanhmaas** [DrewThomasson/ebook2audiobook#148]
Hi,

I'm having some issues when running with Docker. `docker-compose up -d` doesn't seem to generate any logs and I cannot access the UI through the provided port either.

<img width="943" alt="Screenshot 2024-12-28 at 9 55 05 AM" src="https://github.com/user-attachments/assets/56314ee6-e69f-4d69-9cb1-2f47f57d10b1" />

<img width="1250" alt="Screenshot 2024-12-28 at 9 56 31 AM" src="https://github.com/user-attachments/assets/36a4dc89-7a60-4fc1-97c3-d7ba0f21cd50" />

I went through some of the existing issues but couldn't find anything. Any ideas? I even tried running the script with `bash -x` to get the output and got the below.

<img width="568" alt="Screenshot 2024-12-28 at 10 02 07 AM" src="https://github.com/user-attachments/assets/2792393b-bbf8-4d2f-bd0a-922d86b619e6" />

The output of `conda info --base` once I activate an environment is `/opt/homebrew/anaconda3` if that helps.

**Comment by ROBERT-MCDOWELL** [comment]
try to run conda init first.

**Comment by DrewThomasson** [comment]
The Docker repo has been moved to 

[athomasson2/ebook2audiobook](https://hub.docker.com/repository/docker/athomasson2/ebook2audiobook/general)


It's still being held together by essentially bandaids but thats where the latest upcoming updates to it will be located at

**Comment by DrewThomasson** [comment]
The Dockerfile is broken at the moment so the only thing working is the image

and currently the image doesn't use conda so.... idk what that's about

as the docker image is just a pull from this hugginface space atm

https://huggingface.co/spaces/drewThomasson/ebook2audiobook_v2.0_Beta

**Comment by ryanhmaas** [comment]
Thanks for the replies! To close the loop, I had to do the following to get the app running:

- `conda init` 
- `brew install mecab mecab-ipadic` (there was a failure in `python setup.py egg_info` that I traced to that)
