### ISSUE TITLE
Save file location

### ISSUE THREAD

**Issue by Manny8787** [DrewThomasson/ebook2audiobook#150]
I have looked around but I can't see where the files get saved. 
I've need to run this on docker desktop to have access to my GPU but if my computer goes to sleep the browser ui won't show me how the download but I can see in the logs of the container it is either still running or finished. It would be nice to put in the compose where you would like the final save path to be. 

If it is already possible, forgive me. I am  still very new to docker. 
Great container though.

**Comment by luky92** [comment]
for docker at least its saved per seesion in audiobooks folder in the container you can make that folder a volume for easier use i guess

**Comment by ROBERT-MCDOWELL** [comment]
in conf.py, the var audiobooks_dir. set it as you wish

**Comment by luky92** [comment]
> in conf.py, the var audiobooks_gradio_dir, audiobooks_host_dir, audiobooks_cli_dir, set them as you wish

Is it possible to set it in a docker setup?

**Comment by ROBERT-MCDOWELL** [comment]
I think yes, @DrewThomasson will answer to you better than me.

**Comment by clemcer** [comment]
> Is it possible to set it in a docker setup?

Finished audiobooks should be in /home/user/app/audiobooks and the temporary wav files for sentences and chapters in /home/user/app/tmp so you can just map them to whatever folder you want on your system

``
volumes:
          - ${APPDATA}/ebook2audiobook/audiobooks:/home/user/app/audiobooks
          - ${APPDATA}/ebook2audiobook/tmp:/home/user/app/tmp
``

**Comment by DrewThomasson** [comment]
Oh yeah I need to update the readme to include that 😅

**Comment by ROBERT-MCDOWELL** [comment]
ok we consider it solved and close it.

**Comment by DrewThomasson** [comment]
kk I just updated the readme on it

https://github.com/DrewThomasson/ebook2audiobook/blob/main/README.md#docker-container-file-locations

**Comment by DrewThomasson** [comment]
All the files should be located at the base dir of `/home/user/app/`

You'll just need to link that location to a existing folder on your computer 

There should be an example of doing that in the readme and such to add to the `docker run` command

**Comment by Manny8787** [comment]
ok thank you. 
So I could essentially with an input folder drop a file in there and it will be used to then make the audiobook?

**Comment by ROBERT-MCDOWELL** [comment]
in headless mode you have --ebook-dir converting all ebook files from a directory. I'm experimenting to include this option for the gradio GUI mode

**Comment by DrewThomasson** [comment]
> ok thank you. So I could essentially with an input folder drop a file in there and it will be used to then make the audiobook?

yup 

The docker should be able to see the files in that input folder
