### ISSUE TITLE
Unnatural Pauses in German - Incorrect Sentence Splitting

### ISSUE THREAD

**Issue by clemcer** [DrewThomasson/ebook2audiobook#154]
It seems there's an issue with sentence splitting in German, leading to unnatural pauses where none should occur.  

In this image I've highlighted the pauses that are clearly misplaced, as there are no commas or full stops to justify them.

![sentence_splitting_german](https://github.com/user-attachments/assets/63667f31-621c-4d10-b785-1f7c7b1f693f)

**Comment by DrewThomasson** [comment]
Thank you for the helpful visual! 🫶

**Comment by ROBERT-MCDOWELL** [comment]
it's fixed for the next git update and release...

**Comment by ROBERT-MCDOWELL** [comment]
could you provide the real text in chars so I can test on my side?

**Comment by clemcer** [comment]
[german_pauses_test.txt](https://github.com/user-attachments/files/18272374/german_pauses_test.txt)

**Comment by ROBERT-MCDOWELL** [comment]
following this issue to #153
