### ISSUE TITLE
Issue with GPU in docker

### ISSUE THREAD

**Issue by dgb-2000** [DrewThomasson/ebook2audiobook#166]
Running the command `docker run -it --rm --gpus all -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py` I get the following error:

`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

I have an RTX 3070 ti, and my OS is Debian 12. Any Ideas what the issue might be?

**Comment by dgb-2000** [comment]
Sorry for the unecessary issue. Some googling later, it turns out I did not have the Nvidia Container Toolkit installed yet. The guide I used: https://www.server-world.info/en/note?os=Debian_12&p=nvidia&f=2

**Comment by DrewThomasson** [comment]
oh nice well at last this information is here if anyone else runs into that lol 👍
