### ISSUE TITLE
Uncertain on how to add a finetuned model

### ISSUE THREAD

**Issue by basjes1977** [DrewThomasson/ebook2audiobook#168]
First of all thanks for this nice tool!
I've succesfully setup the docker compose version and have been tinkering with it. 
I've also created a finetuned XTTS model, but when uploading it, I do not see an option to use it.
I did follow the hint of creating a zip file: "

> *Custom XTTS Model (a .zip containing config.json, vocab.json, model.pth, ref.wav)

"

What am I missing?

**Comment by DrewThomasson** [comment]
well I did just change the docker-config file back to the original but....

I'm still having this issue even with the docker run command...

@ROBERT-MCDOWELL 

is this a known issue?

**Comment by DrewThomasson** [comment]
@basjes1977 

Also you said you've been messing with the docker-config file?

Any suggestions for stuff I should add to it?

**Comment by ROBERT-MCDOWELL** [comment]
it's a known bug, It's solved for the next push/update/release

**Comment by DrewThomasson** [comment]
Kk I'll close this then 👌

**Comment by basjes1977** [comment]
> @basjes1977
> 
> Also you said you've been messing with the docker-config file?
> 
> Any suggestions for stuff I should add to it?

Nope I already saw you made voluem mapping ;)
