### ISSUE TITLE
can't run app.py

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [DrewThomasson/ebook2audiobook#36]
hello, i'm trying to run app.py, but this is what the terminal outputs:

```
C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS>python app.py
starting...
Traceback (most recent call last):
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\app.py", line 94, in <module>
    import nltk
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\nltk\__init__.py", line 138, in <module>
    from nltk.text import *
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\nltk\text.py", line 30, in <module>
    from nltk.tokenize import sent_tokenize
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\nltk\tokenize\__init__.py", line 66, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\nltk\tokenize\casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
    ^^^^^^^^^^^^
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\regex\regex.py", line 417, in <module>
    import regex._regex_core as _regex_core
  File "C:\windows-python3.10-ebook2audiobookxtts\ebook2audiobookXTTS\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

i've followed all the installation steps, and made sure the [regex module](https://pypi.org/project/regex/) is installed after reading the [issue the terminal references](https://github.com/nltk/nltk/issues/2409) but same result. would you know how to fix this? thank you

**Comment by DrewThomasson** [comment]
what does running the command

```bash
python -m pip show regex
```

give you?

**Comment by DrewThomasson** [comment]
Try:

```bash
python -m pip install regex -v; python -m pip show regex; python -c "import regex; print('regex imported successfully')"

```

What happens?

**Comment by ROBERT-MCDOWELL** [comment]
ebook2audiobook is not compatible with 3.12 and 3.13 since all major A.I. engine runs < 3.12 unless very few exception.
you must for now install a python virtual env version 3.10 or 3.11. or wait the new release as an installer will do that for you

**Comment by DrewThomasson** [comment]
@cavalrymargarine0x1 

so yeah, Right now were working on getting to out version 2.0 which will be a lot easer to install.

In the meantime you can run it in the docker version:

### 🐳 Using Docker

You can also use Docker to run the eBook to Audiobook converter. This method ensures consistency across different environments and simplifies setup.

#### 🚀 Running the Docker Container

To run the Docker container and start the Gradio interface, use the following command:

 -Run with CPU only
```powershell
docker run -it --rm -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
```
 -Run with GPU Speedup (Nvida graphics cards only)
```powershell
docker run -it --rm --gpus all -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
```

This command will start the Gradio interface on port 7860.(localhost:7860)

**Comment by DrewThomasson** [comment]
This should be fixed in version 2.0 which we just released

try again if your issue persists you can re-open this issue :)

**Comment by chrischma** [comment]
> This should be fixed in version 2.0 which we just released
> 
> try again if your issue persists you can re-open this issue :)

sorry – *not* fixed.

**Comment by ROBERT-MCDOWELL** [comment]
@chrischma run eb2ab from app.py is deprecated, you should run it from ebook2audiobook.sh for linux and .cmd for windows

**Comment by Alpha-chen** [comment]
> @chrischma run eb2ab from app.py is deprecated, you should run it from ebook2audiobook.sh for linux and .cmd for windows as this you don't have to care of anything concerning python packages, it's installed automatically under a python env.

i got this error

**Comment by Alpha-chen** [comment]
> @chrischma run eb2ab from app.py is deprecated, you should run it from ebook2audiobook.sh for linux and .cmd for windows as this you don't have to care of anything concerning python packages, it's installed automatically under a python env.

i got this error  when use ./ebook2audiobook.sh 


./ebook2audiobook.sh 
Running in native mode
Traceback (most recent call last):
  File "/home/x/code/ebook2audiobook/app.py", line 3, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'

**Comment by ROBERT-MCDOWELL** [comment]
this is a know bug fixed in the next update. for now go to eb2ab folder, then
conda activate ./python_en
pip install regex
conda deactivate

**Comment by Alpha-chen** [comment]
> this is a know bug fixed in the next update. for now go to eb2ab folder, then conda activate ./python_en pip install regex conda deactivate

it's ok .

**Comment by Alpha-chen** [comment]
> this is a know bug fixed in the next update. for now go to eb2ab folder, then conda activate ./python_en pip install regex conda deactivate

it's ok ,but i got another error 


 Using cached mecab-0.996.5.tar.gz (64 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      /bin/sh: 1: mecab-config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wg76qnzq/mecab_6a6a9b13f8b1415ebcf475aa01f92631/setup.py", line 49, in <module>
          include_dirs=cmd2("mecab-config --inc-dir"),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-wg76qnzq/mecab_6a6a9b13f8b1415ebcf475aa01f92631/setup.py", line 19, in cmd2
          return cmd1(strings).split()
                 ^^^^^^^^^^^^^
        File "/tmp/pip-install-wg76qnzq/mecab_6a6a9b13f8b1415ebcf475aa01f92631/setup.py", line 15, in cmd1
          return os.popen(strings).readlines()[0].rstrip()
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed to install packages: Command '['/home/x/code/ebook2audiobook/python_env/bin/python', '-m', 'pip', 'install', '--upgrade', 'pip', 'beautifulsoup4', 'coqui-tts', 'cutlet', 'deep_translator', 'docker', 'ebooklib', 'gensim', 'gradio>=4.44', 'hangul-romanize', 'indic-nlp-library', 'iso-639', 'jieba', 'm4b-util', 'mecab', 'mecab-python3', 'pydub', 'pypinyin', 'ray', 'transformers', 'translate']' returned non-zero exit status 1.
Some packages could not be installed

**Comment by ROBERT-MCDOWELL** [comment]
conda activate ./python_en
pip install mecab mecab-python3
conda deactivate

**Comment by ROBERT-MCDOWELL** [comment]
install on your OS mecab mecab-devel mecab-ipadic and see if it's better

**Comment by Alpha-chen** [comment]
> install on your OS mecab mecab-devel mecab-ipadic and see if it's better

Yes ,i resolve this error .

my system is Linux x-click 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

sudo apt-get update
sudo apt-get install mecab libmecab-dev mecab-ipadic-utf8

**Comment by ROBERT-MCDOWELL** [comment]
ok, so it confirms the fix for the next update. thanks

**Comment by chrischma** [comment]
> > @chrischma run eb2ab from app.py is deprecated, you should run it from ebook2audiobook.sh for linux and .cmd for windows as this you don't have to care of anything concerning python packages, it's installed automatically under a python env.
> 
> i got this error when use ./ebook2audiobook.sh
> 
> ./ebook2audiobook.sh Running in native mode Traceback (most recent call last): File "/home/x/code/ebook2audiobook/app.py", line 3, in import regex as re ModuleNotFoundError: No module named 'regex'

yes, same here. i am using the sh script aswell.

**Comment by noctis711** [comment]
> @cavalrymargarine0x1
> 
> so yeah, Right now were working on getting to out version 2.0 which will be a lot easer to install.
> 
> In the meantime you can run it in the docker version:
> 
> ### 🐳 Using Docker
> You can also use Docker to run the eBook to Audiobook converter. This method ensures consistency across different environments and simplifies setup.
> 
> #### 🚀 Running the Docker Container
> To run the Docker container and start the Gradio interface, use the following command:
> 
> -Run with CPU only
> 
> ```powershell
> docker run -it --rm -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
> ```
> 
> -Run with GPU Speedup (Nvida graphics cards only)
> 
> ```powershell
> docker run -it --rm --gpus all -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
> ```
> 
> This command will start the Gradio interface on port 7860.(localhost:7860)

How do I resolve this error?  I tried installing the nvidia container toolkit but it did not help. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installation

docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
