### ISSUE TITLE
Feature Requests! 

### ISSUE THREAD

**Issue by quantumlump** [DrewThomasson/ebook2audiobook#38]
Obviously no expectation that you do these but here are some requests!

1. Batch processing - Allow for loading in multiple books so that the app starts working on the next book immediately
2. Do not reset the UI on refresh - Right now if I mistakenly reload the web UI, it resets to the default screen (even though the tts is still working in the terminal). This means I can't download the file once it is done from the web UI (have to find it in the Docker files lol)
3. Ability to set a default output folder for the audiobooks (automatic downloading) 

Thx!

**Comment by ROBERT-MCDOWELL** [comment]
1. it's done on the next version
2. todo indeed. I started to develop it but not happy from the result and retracted the modif. we should go deeper to find a good compromise.
3. it's done on the next version, output folder where all conversion go will be audiobooks.

**Comment by scriptpony** [comment]
Awesome! Another huge addition would be the ability to use the new F5-TTS model. It seems to have less hallucinations.

**Comment by DrewThomasson** [comment]
Good idea! 👍 

- We do plan on integrating other tts services into ebook2audiobook.
- But it's being put on the back-end until we figure out a standardized way of integrating many different tts engines into ebook2audiobook

**Comment by scriptpony** [comment]
Best of luck!

**Comment by DrewThomasson** [comment]
## About #2 though,

Are you not able to click the download audiobooks button in the GUI to load download links to all the generated audiobook files in the output folder?

Cause that button should be doing that which would technically solve the issue? 🤔

**Comment by scriptpony** [comment]
I can do that! But then how can I easily access the files there?

**Comment by scriptpony** [comment]
Okay that is awesome, I never thought about clicking that button 😅. Maybe those should load automatically or work like a drop down menu in the UI? Or maybe I should learn to read better lol

**Comment by ROBERT-MCDOWELL** [comment]
@scriptpony it's on the way also in the next version

**Comment by DrewThomasson** [comment]
## Short answer: gradio is extremely restrictive in reloading anything in the gui.

- Easiest is to just give the user a reload/update button at the moment lol


## I'll look at renaming the button to make it more clear on what it does tho lol,

- That would probs help

**Comment by DrewThomasson** [comment]
### Perhaps renamed to

## "View Completed Audiobooks" ? 🤔

**Comment by ROBERT-MCDOWELL** [comment]
or converted files folder

**Comment by scriptpony** [comment]
Awesome 

Maybe "refresh outputs folder" or something like that to make it clear that it doesn't come up automatically.

**Comment by scriptpony** [comment]
actually "Show Converted AudioBooks" would probably be better

**Comment by scriptpony** [comment]
Show converted files or audiobooks would make most sense to me!

**Comment by DrewThomasson** [comment]
Changed to "Show Converted Files"

https://github.com/DrewThomasson/ebook2audiobookXTTS/commit/905cb2144c7daef806b6037d0335f620141bfe5e

:)

**Comment by ROBERT-MCDOWELL** [comment]
app.py is completely differente since the start of the PR, now run_gradio_interface() is in functions.py file and named web_interface(), so github completely mess up the conflict here.... :-\

**Comment by jondana** [comment]
After a lot of trial and error I was able to modify your code to get it working with F5-TTS! 

I am running into issues getting it on Hugging Face (I am new to this) but here it is if you wanted to check it out:
https://drive.google.com/file/d/1tWWxoPX66JOoHcZVkf3idx9ZNpU28g9n/view?usp=sharing

**Comment by DrewThomasson** [comment]
👀

**Comment by DrewThomasson** [comment]
If you make a fork of it and then apply those changes to your fro

**Comment by DrewThomasson** [comment]
If you make a fork of this repo and then apply your changes it'll be easier for us to be able too see your changes you made to it

In the meantime were hard at work on a version 2.0 where the code base is heavily modified 😅 

I'll look into your code tho to see how it preforms!

Well probs look into asking you for help in the future when adding it smoothly to ebook2audiobook v2.0

**Comment by DrewThomasson** [comment]
I'll give you a heads up on the functions we would need you to make once we get our v2.0 stuff finalized 😅 

## In the meantime Here is me testing out your code as a hugginface space

https://huggingface.co/spaces/drewThomasson/ebook2audiobook_F5-TTS

**Comment by jondana** [comment]
Awesome! Glad it works on hf. Fair warning the code is hot garbage chatGPT slop but it works so 🤷‍♂️. I just wanted to get something working asap 

Super slow on CPU btw, actually idk if it even works on CPU I didn't test that

**Comment by ROBERT-MCDOWELL** [comment]
I works well on CPU, fore sure much slower but ok. the feature 2. is developed on v2.0.0 but only in cas of crash on server side, not client. meaning that if the gradio client is losing the conection but the process is still running on server side so it's still not possible to reconnect gradio to the same process, and I'm not sure it's possible unless with a deep code dev.

**Comment by jondana** [comment]
NEXT VERSION!

https://github.com/jondana/eBook_to_Audiobook_with_F5-TTS/tree/main

- Batch convert eBooks
- Pull the cover image correctly and place it in mp3 "icon" slot (I was having trouble with your .m4b files stopping randomly in my audiobook player?) mp3 seems more stable
- Updated inferencing for more natural phrasing with better pauses
- UI improvements

I spent way too much time trying to improve the progress bar to show wav stitching but didn't work out
I also tried to make an estimated time to completion feature but also didn't work out (I feel like Gradio should have that feature built in?? total steps/seconds to complete each step)

**Comment by ROBERT-MCDOWELL** [comment]
don't waste too much your effort on the actual version, the next version is full code rebase and integrate what you did in the v2 version will be a lot of complications. better you wait the v2 then you can push a PR.

**Comment by DrewThomasson** [comment]
Agreed🫡😅

**Comment by DrewThomasson** [comment]
Updated the hugging face demo of ur code though in the meantime 

https://huggingface.co/spaces/drewThomasson/ebook2audiobook_F5-TTS

**Comment by leet1994** [comment]
Is point 3 already implemented?

> 3. Ability to set a default output folder for the audiobooks (automatic downloading)

**Comment by ROBERT-MCDOWELL** [comment]
@leet1994 yes, it's in ./lib/conf.py, change it to your own.

**Comment by ROBERT-MCDOWELL** [comment]
@quantumlump 
1. DONE
2. DONE, but when a refresh is done, you have to restart the conversion, and it will resume automatically from the next good sentence.
3. DONE check ./lib/conf.py "audiobooks_dir" variable.
Be aware that the next git update conf.py will be modified so you will have to reset it again.
