### ISSUE TITLE
multivoice for one ebook. Detect persona in text, and use personal voice.

### ISSUE THREAD

**Issue by pivolan** [DrewThomasson/ebook2audiobook#53]
Breaking down text into segments and assigning specific voice roles for narration, so that different parts of the text are voiced by different characters - for example, having distinct voices for dialogues. This approach to audio narration helps create a more dynamic and engaging listening experience by using different voice actors or voice types for various parts, similar to how a radio play or audiobook might have separate voices for the narrator and each character's dialogue.

**Comment by DrewThomasson** [comment]
Are you just describing my older expirimental VoxNovel project? 😅 

https://github.com/DrewThomasson/VoxNovel

**Comment by DrewThomasson** [comment]
idk perhaps I'll eventually integrate it into this project 🤔 

Anyway I guess that helps you out?.... I'll just close this issue out thennn

**Comment by ROBERT-MCDOWELL** [comment]
@pivolan it's not an easy task to do it for a global feature as it really depend of the text, the language and how the book is written. unless to search fo pronouns like "he" "she", we still can't guess the age (child? elder?), etc...
nontheless, if the ebook clearly has markup for each piece of text the task can be easier.
I started weeks ago to develop this feature but was not really satisfied so for now it's in standby and maybe it will be in an update of the version 2.x.x.
