### ISSUE TITLE
need to agree to COQUI TTS license

### ISSUE THREAD

**Issue by voipworld** [DrewThomasson/ebook2audiobook#54]
hello developer,
thank you for this great project, i'm trying to benefit from it as a blind users loving to listen to audio books.
after runing the web ui and launching a convertion process, i get a prompt to agree to the COQUI TTS license either i have a commercial or a community license.
either typing y or n give nothing, just throw the exception that i need to agree.
for the fix, i added the following befaure the device detection line:
os.environ["COQUI_TOS_AGREED"] = "1"
thank you!

**Comment by DrewThomasson** [comment]
Thank you for the info!

This is actually going to be fixed once we release v.2.0 

Using the same method you have described 😄 ❤️
