### ISSUE TITLE
v2 branch Test

### ISSUE THREAD

**Issue by agentxan** [DrewThomasson/ebook2audiobook#78]
v2 branch Commit 046e007
First just wanted to say thank you for your work on this. It is looking great.

I am using Windows 11 with a Nvidia RTX 3060 12gb
I used ebook2audiobook.cmd which set up the environment but it only would use the cpu.
I tried installing torch using the command from the pytorch website 

conda activate ./python_env
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
conda deactivate

Then I got the following error

trying gpu
convert_ebook() Exception: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, maia, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: gpu

I added this to function.py which allowed the gpu to be used     
if device == 'gpu':
  device = 'cuda'

The individual chapter wav files were generated fine but when combined into the final m4b file the chapter sorting got mixed up. In the final file the 33 chapters were in this order

1
10
11
12
13
14
15
16
17
18
19
2
20
21
22
23
24
25
26
27
28
29
3
30
31
32
33
4
5
6
7
8
9

**Comment by DrewThomasson** [comment]
Mmmmm Very intresting 

I didn't expect anyone to check in on our v2.0 work XD

- fantastic to know that the install worked 


I'll hit Robert up on this as he's assigned to the functions.py file right now 👍

Yo @ROBERT-MCDOWELL

**Comment by DrewThomasson** [comment]
Thank you so much for this information, this is very helpful 👍

**Comment by ROBERT-MCDOWELL** [comment]
It's fixed on my fork, I need to prepare a PR  on Drew repo... thanks for your report!

**Comment by DrewThomasson** [comment]
I'll just be closing this issue thennnn cause it appears to be solved..... :)
